services:
  homeassistant:
    container_name: schwoerer-wgt-controller-ha-test
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
      - ./custom_components/schwoerer_wgt_controller:/config/custom_components/schwoerer_wgt_controller
      - ../homeassistant-schwoerer-lueftung/custom_components/schwoerer_lueftung:/config/custom_components/schwoerer_lueftung
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: bridge
    ports:
      - "8124:8123"
