name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

jobs:
  ci:
    uses: josa42/gha-workflows/.github/workflows/ha-integration.yml@main
    with:
      python_version: "3.12"
      hacs_ignore: topics description brands
